config/routes.rb
Rails.application.routes.draw do
  root 'epicenter#feed'
  
  get 'show_user' => 'epicenter#show_user'

  get 'now_following' => 'epicenter#now_following'

  get 'unfollow' => 'epicenter#unfollow'
  get 'tag_mews' => 'epicenter#tag_mews'
  resources :mews
  devise_for :users
  

end

app/models/mew.rb
class Mew < ActiveRecord::Base
    belongs_to :user
    
    has_many :mew_tags
    has_many :tags, through: :mew_tags
    
  validates :message,  presence: true, length: {maximum: 140, 
too_long: "A tweet is only 140 max. Everybody knows that!"}
    


end

app/models/mew_tag.rb
class MewTag < ActiveRecord::Base
end

app/models/tag.rb
class Tag < ActiveRecord::Base
    
    has_many :mew_tags
    has_many :mews, through: :mew_tags
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
         has_many :mews
         validates :username, presence: true, uniqueness:true
         serialize :following, Array
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :authenticate_user!  

before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters

    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit({ roles: [] }, :email, :password, :password_confirmation, :name, :username, :bio, :location, :following) }

    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:email, :password, :password_confirmation, :current_password, :name, :username, :bio, :location, :following) }

  end



end

app/controllers/epicenter_controller.rb
class EpicenterController < ApplicationController
  
  
  
  def feed
    
    @following_mews = []
    
    Mew.all.each do |mew|
      if current_user.following.include?(mew.user_id)
        @following_mews.push(mew)
      end
    end
    
  end

  def show_user
    @user = User.find(params[:id])
  end

  def now_following
    @user = User.find(params[:id].to_i)
    
    current_user.following.push(params[:id].to_i)
    current_user.save
  end

  def unfollow
     @user = User.find(params[:id].to_i)
    
    current_user.following.delete(params[:id].to_i)
    current_user.save
  end
end

  def create 
    @mew = Mew.create.(mew_params)
   
    
    @mew.update(message: message_arr.join(""))
    
   
    
    
  end
  
  def tag_mews
    @tag = Tag.find(params[:id])
  end

app/controllers/mews_controller.rb
class MewsController < ApplicationController
  before_action :set_mew, only: [:show, :edit, :update, :destroy]

include MewsHelper

before_filter :authenticate_user!

  # GET /mews
  # GET /mews.json
  def index
    @mews = Mew.all
  end

  # GET /mews/1
  # GET /mews/1.json
  def show
  end

  # GET /mews/new
  def new
    @mew = Mew.new
  end

  # GET /mews/1/edit
  def edit
  end

  # POST /mews
  # POST /mews.json
  def create
    @mew = Mew.new(mew_params)
    
    
    @mew = get_tagged(@mew)

    respond_to do |format|
      if @mew.save
        format.html { redirect_to @mew, notice: 'Mew was successfully created.' }
        format.json { render :show, status: :created, location: @mew }
      else
        format.html { render :new }
        format.json { render json: @mew.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mews/1
  # PATCH/PUT /mews/1.json
  def update
    respond_to do |format|
      if @mew.update(mew_params)
        format.html { redirect_to @mew, notice: 'Mew was successfully updated.' }
        format.json { render :show, status: :ok, location: @mew }
      else
        format.html { render :edit }
        format.json { render json: @mew.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mews/1
  # DELETE /mews/1.json
  def destroy
    @mew.destroy
    respond_to do |format|
      format.html { redirect_to mews_url, notice: 'Mew was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mew
      @mew = Mew.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mew_params
      params.require(:mew).permit(:message, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/epicenter_helper.rb
module EpicenterHelper
end

app/helpers/mews_helper.rb
module MewsHelper
    def get_tagged(mew)
         message_arr = mew.message.split
         message_arr.each_with_index do |word, index|
            if word[0] == "#"
                if Tag.pluck(:phrase).include?(word)
                    tag = Tag.find_by(phrase: word)
                else
                    tag = Tag.create(phrase: word)
                end
                mew_tag = MewTag.create(mew_id: mew.id, tag_id: tag.id)
                message_arr.delete(word)
                message_arr[index] = "<a href='/tag_mews?id=#{tag.id}'>#{word}</a>"
            end
        end

        mew.message = message_arr.join(" ")
        return mew
    end

end

app/views/epicenter/feed.html.erb
<h1><%= current_user.username %>'s Mews!</h1>

<div class="panel panel-default">
    
    <div class="panel-heading" >   
     
     <p>who is Mewing?</p>
    </div>
    
    
    <div class="panel-body">
    
    <div class="row">
    
    <% @following_mews.each do |mew| %>
     
     <div class="col-md-4">
         <div class="well"></div>
            <p><%= mew.message %></p>
            <p><%= mew.user.username %></p>
        </div>
        
        <% end %>
       </div>
       
</div>
<div class="panel-footer">

app/views/epicenter/now_following.html.erb
<h1>You are now following <%= @user.username %></h1>
<p>bloooooooooooooooooooooooooooooooooooooooooop</p>

app/views/epicenter/show_user.html.erb
<h1><%= @user.username %>'s Profile &amp; Mews</h1>

<p><%= @user.name %></p>
<p><%= @user.location %></p>
<p><%= @user.bio %></p>
  
  <% if current_user.id != @user.id %>
 
<p>
  <% if current_user.following.include?(@user.id) %>
        <%= link_to "Following", unfollow_path(id: @user.id), class: "btn btn-primary", id: "unfollow-btn" %>
    <% else %>
    <%= link_to "Follow", now_following_path(id: @user.id), class: "btn btn-primary" %>
    <% end %>
</p>
<% end %>
<% @user.mews.each do |mew| %>
<div>
    <p><%= mew.message %></p>
    <p><%= mew.user.username %></p>
</div>
<% end %>

<script>
  $(document).ready(function(){
    $("#unfollow-btn").hover(function(){
      $(this).removeClass("btn-primary");
      $(this).addClass("btn-danger");
      $(this).html("Unfollow");
    }, function(){
      $(this).html("Following");
      $(this).removeClass("btn-danger");
      $(this).addClass("btn-primary");
    });
  })
</script>

app/views/epicenter/tag_mews.html.erb
<div class="center-it tag-topic-header">
    <h1><%= @tag.phrase %></h1>
</div>

<div class="row">
    <!-- a place for current user stats -->
    <div class="col-md-7 col-md-offset-1">
	<div class="row">
	    <% @tag.mews.order(created_at: :desc).each do |mew| %>
	        <div class="col-md-12 tweet-area borderline">
		    <p>
		        <%= link_to show_user_path(id: mew.user.id) do %> 
			    <%= mew.user.name %> <span class="no-underline">
                              <%= "@#{mew.user.username}" %></span>
		        <% end %>
			 <%= time_ago_in_words(mew.created_at) %>
		    </p>
		    <p><%= mew.message.html_safe %></p>
		</div>
	    <% end %>
	</div>
    </div>
</div>

app/views/epicenter/unfollow.html.erb
<h1>you are no longer following</h1>
<p> <%= @user.username %> </p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
 <meta http-equiv="X-UA-Compatible" content="IE=edge">
 <meta name="viewport" content="width=device-width, initial-scale=1">
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css">
 <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
  <link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet">
  <title>Workspace</title>
  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= image_tag "supercat.gif", class: "img"%>
       <%= link_to "Good Mews!", mews_path, class: "btn btn-default"%>
      <%= link_to "Your feed", root_path, class: "btn btn-default"%>
      <h6>     </h6>
      
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

        
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-user"></span></a>
          <ul class="dropdown-menu">
            <% if user_signed_in? %>
               <li><%= link_to "Edit Profile", edit_user_registration_path %> </li>
               <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
             
             <% else %>
               <li><%= link_to "Sign-up", new_user_registration_path %></li>
               <li><%= link_to "Forgot Password", new_user_password_path %></li>
             
            <% end %>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>



<div class="container">
<%= yield %>
</div>
</body>
</html>

app/views/mews/_form.html.erb
<%= form_for(@mew) do |f| %>
  <% if @mew.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mew.errors.count, "error") %> prohibited this mew from being saved:</h2>

      <ul>
      <% @mew.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_field :message %>
  </div>
  <div class="field">
    <%= f.hidden_field :user_id, value: current_user.id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mews/edit.html.erb
<h1>Editing Mew</h1>

<%= render 'form' %>

<%= link_to 'Show', @mew %> |
<%= link_to 'Back', mews_path %>

app/views/mews/index.html.erb
<p id="notice"><%= notice %></p>

<div class="panel panel-default">
  
  <div class="panel-heading">

    <h1>Listing Mews</h1>
  </div>
 
 <div class=class="panel-body">
  
  <div class="row">
    
    <% @mews.each do |mew| %>
      
      <div class="col-md-4">
        <div class="well">
        
        
        <h4><%= link_to mew.user.username, show_user_path(id: mew.user.id) %></h4>
        <p><%= mew.message %></p>

        <p>
          <% if current_user.id != mew.user.id %>
          <%= link_to 'Show', mew %>
          <% else %>
          <% link_to 'Show', mew %>
        <%= link_to 'Edit', edit_mew_path(mew) %>
        <%= link_to 'Destroy', mew, method: :delete, data: { confirm: 'Are you sure?' } %>
    
       <% end %>
      </p>
    </div>
  </div>
<% end %>
    </div>

<div class="panel-footer">
<%= link_to 'New Mew', new_mew_path, class: "btn btn-default"%>
</div>
</div>

app/views/mews/new.html.erb
<h1>New Mew</h1>

<%= render 'form' %>

<%= link_to 'Back', mews_path %>

app/views/mews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Message:</strong>
  <%= @mew.message %>
</p>


 <p>
	<strong>User:</strong>
		<%= link_to @mew.user.username, 
                    show_user_path(id: @mew.user.id) %>

</p>

<%= link_to 'Edit', edit_mew_path(@mew) %> |
<%= link_to 'Back', mews_path %>